# Simple Docker Compose with minimal nginx configuration
# Use if the main docker-compose.yml has nginx issues
# Run with: docker-compose -f docker-compose.simple.yml up

version: '3.8'

services:
  # Flask API Backend
  api:
    build: 
      context: ./arrow_scraper
      dockerfile: Dockerfile
    container_name: arrowtuner-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    volumes:
      - ./arrow_scraper:/app
      - arrowtuner-data:/app/data
    networks:
      - arrowtuner-network

  # Nuxt 3 Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: arrowtuner-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://api:5000/api
    depends_on:
      - api
    networks:
      - arrowtuner-network

  # Minimal Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: arrowtuner-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.minimal.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend
    networks:
      - arrowtuner-network

volumes:
  arrowtuner-data:
    driver: local

networks:
  arrowtuner-network:
    driver: bridge